### ISSUE TITLE
Creating release fails on Python 3

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/i18ndude#101]
We have a `zest.releaser` hook for updating the documentation. It fails on Python 3:

```
$ fullrelease
INFO: Starting prerelease.
Traceback (most recent call last):
  File "/Users/maurits/bin/fullrelease", line 33, in <module>
    sys.exit(load_entry_point('zest.releaser', 'console_scripts', 'fullrelease')())
  File "/Users/maurits/zest.releaser/zest/releaser/fullrelease.py", line 23, in main
    prereleaser.run()
  File "/Users/maurits/zest.releaser/zest/releaser/baserelease.py", line 412, in run
    self._run_hooks("before")
  File "/Users/maurits/zest.releaser/zest/releaser/baserelease.py", line 409, in _run_hooks
    utils.run_hooks(self.setup_cfg, which_releaser, when, self.data)
  File "/Users/maurits/zest.releaser/zest/releaser/utils.py", line 592, in run_hooks
    hook(data)
  File "/Users/maurits/tools/src/i18ndude/src/i18ndude/utils.py", line 227, in prepare_cli_documentation
    result.extend(indent(res))
  File "/Users/maurits/tools/src/i18ndude/src/i18ndude/utils.py", line 216, in indent
    result.append('  ' + line)
TypeError: can only concatenate str (not "bytes") to str
```

If I use a `fullrelease` from Python 2, it works. I will use that now.
Easiest way to fix this, is to drop Python 2 support in i18ndude, and fix this code for Python 3 only.

Note that this error does not matter at all for end users.

**Comment by gforcada** [comment]
I'm having a bit of a different error:

```shell
git clone git@github.com:collective/i18ndude
cd i18ndude
python -m venv venv
. venv/bin/activate
pip install -e . 
pip install zest.releaser[recommended]
fullrelease
```

Doing all the above leads to the following traceback:

```
INFO: Starting prerelease.
Traceback (most recent call last):
  File "/home/gil/Documents/plone/i18ndude/venv/bin/fullrelease", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/gil/Documents/plone/i18ndude/venv/lib64/python3.11/site-packages/zest/releaser/fullrelease.py", line 23, in main
    prereleaser.run()
  File "/home/gil/Documents/plone/i18ndude/venv/lib64/python3.11/site-packages/zest/releaser/baserelease.py", line 430, in run
    self._run_hooks("before")
  File "/home/gil/Documents/plone/i18ndude/venv/lib64/python3.11/site-packages/zest/releaser/baserelease.py", line 427, in _run_hooks
    utils.run_hooks(self.setup_cfg, which_releaser, when, self.data)
  File "/home/gil/Documents/plone/i18ndude/venv/lib64/python3.11/site-packages/zest/releaser/utils.py", line 605, in run_hooks
    hook(data)
  File "/home/gil/Documents/plone/i18ndude/src/i18ndude/utils.py", line 226, in prepare_cli_documentation
    res = subprocess.check_output([base_cmd, '--help'])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.11/subprocess.py", line 1917, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'bin/i18ndude'
```

Oh, now I see, if on the first commands I do `python -m venv .` then I get the same traceback:

```
INFO: Starting prerelease.
Traceback (most recent call last):
  File "/home/gil/Documents/plone/i18ndude/bin/fullrelease", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/gil/Documents/plone/i18ndude/lib64/python3.11/site-packages/zest/releaser/fullrelease.py", line 23, in main
    prereleaser.run()
  File "/home/gil/Documents/plone/i18ndude/lib64/python3.11/site-packages/zest/releaser/baserelease.py", line 430, in run
    self._run_hooks("before")
  File "/home/gil/Documents/plone/i18ndude/lib64/python3.11/site-packages/zest/releaser/baserelease.py", line 427, in _run_hooks
    utils.run_hooks(self.setup_cfg, which_releaser, when, self.data)
  File "/home/gil/Documents/plone/i18ndude/lib64/python3.11/site-packages/zest/releaser/utils.py", line 605, in run_hooks
    hook(data)
  File "/home/gil/Documents/plone/i18ndude/src/i18ndude/utils.py", line 227, in prepare_cli_documentation
    result.extend(indent(res))
                  ^^^^^^^^^^^
  File "/home/gil/Documents/plone/i18ndude/src/i18ndude/utils.py", line 216, in indent
    result.append('  ' + line)
                  ~~~~~^~~~~~
TypeError: can only concatenate str (not "bytes") to str
```

Now I can fix it 😄
