### ISSUE TITLE
RunTimeError: OrderedDict mutated during iteration

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/i18ndude#49]
On Python 3, with the merge of PR #48, you may run into an error during sync:

```
$ ~/tools/src/i18ndude/bin/i18ndude sync --pot widgets.pot */*/widgets.po .
Traceback (most recent call last):
  File "/Users/maurits/tools/src/i18ndude/bin/i18ndude", line 16, in <module>
    sys.exit(i18ndude.script.main())
  File "/Users/maurits/tools/src/i18ndude/src/i18ndude/script.py", line 715, in main
    errors = arguments.func(arguments)
  File "/Users/maurits/tools/src/i18ndude/src/i18ndude/script.py", line 452, in sync
    added_msgids, removed_msgids = po.sync(pot_ctl)
  File "/Users/maurits/tools/src/i18ndude/src/i18ndude/catalog.py", line 316, in sync
    for msgid in self.accept_ids(msgctl.keys())]
  File "/Users/maurits/tools/src/i18ndude/src/i18ndude/catalog.py", line 343, in accept_ids
    for key in self.keys():
RuntimeError: OrderedDict mutated during iteration
```

See my comment in that PR at https://github.com/collective/i18ndude/pull/48#issuecomment-370372949.

To reproduce:

- Go to a `plone.app.locales` master checkout, and directory `plone/app/locales/locales`.
- `git checkout ca8aeda8360216b667cb92e3874d76ba5f820884`
- `i18ndude sync --pot widgets.pot nl/LC_MESSAGES/widgets.po .` ( or `*/*/widgets.po`)

The problem is that the `widgets.pot` file contains a msgid `there was an error performing the action` and the `po` files have a msgid  `there was an error performing action`, so missing `the`. There are probably other ways to trigger this.

I fixed the immediate problem manually in https://github.com/collective/plone.app.locales/commit/ce55662d8abb27c1fd844cc63d4d87be796fe7ad, but it should be fixed generally.

So I think it boils down to this: if a po file contains a msgid which is *not* in the pot file, then you get this error.  But: only on Python 3.

Possibly related: issue #47.

cc @gyst

**Comment by mauritsvanrees** [comment]
Okay, simply adding this to a `po` file and then calling `sync` on it in Python 3 is enough:

```
msgid "foo bar"
msgstr ""
```
