### ISSUE TITLE
UnicodeEncodeError on i18ndude 5.0.2

### ISSUE THREAD

**Issue by gforcada** [collective/i18ndude#55]
See https://jenkins.plone.org/view/Translations/job/plone-5.2-i18n/2/console

```
+ ../../../../../../bin/i18ndude list -p plone
Traceback (most recent call last):
  File "../../../../../../bin/i18ndude", line 16, in <module>
    sys.exit(i18ndude.script.main())
  File "/home/jenkins/.buildout/eggs/i18ndude-5.0.2-py2.7.egg/i18ndude/script.py", line 715, in main
    errors = arguments.func(arguments)
  File "/home/jenkins/.buildout/eggs/i18ndude-5.0.2-py2.7.egg/i18ndude/script.py", line 682, in arg_list
    visualisation.make_listing(pot_ctl, po_catalogs, table=table)
  File "/home/jenkins/.buildout/eggs/i18ndude-5.0.2-py2.7.egg/i18ndude/visualisation.py", line 197, in make_listing
    output_list(values.copy(), languagelist, total)
  File "/home/jenkins/.buildout/eggs/i18ndude-5.0.2-py2.7.egg/i18ndude/visualisation.py", line 126, in output_list
    aligned_print(out[code]['percentage'], out[code]['desc'])
  File "/home/jenkins/.buildout/eggs/i18ndude-5.0.2-py2.7.egg/i18ndude/visualisation.py", line 116, in aligned_print
    print("%s%% - %s" % (percentage, desc))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 11: ordinal not in range(128)
```

**Comment by mauritsvanrees** [comment]
It could help to set an environment variable:

    export PYTHONIOENCODING=utf-8

That seems needed when you pipe or redirect the output. See [my comment](https://github.com/collective/i18ndude/issues/51#issuecomment-372278905).

I see the same locally when I use an empty/dummy grep:

```
$ i18ndude list -p plone | grep ''
Traceback (most recent call last):
  File "/Users/maurits/tools/bin/i18ndude", line 16, in <module>
Messages: 2806
    sys.exit(i18ndude.script.main())

Tier 1:

100% - English (en)
 90% - French (fr)
 90% - Italiano (it)
  File "/Users/maurits/tools/src/i18ndude/src/i18ndude/script.py", line 715, in main
 83% - Deutsch (de)
    errors = arguments.func(arguments)
  File "/Users/maurits/tools/src/i18ndude/src/i18ndude/script.py", line 682, in arg_list
    visualisation.make_listing(pot_ctl, po_catalogs, table=table)
  File "/Users/maurits/tools/src/i18ndude/src/i18ndude/visualisation.py", line 197, in make_listing
    output_list(values.copy(), languagelist, total)
  File "/Users/maurits/tools/src/i18ndude/src/i18ndude/visualisation.py", line 126, in output_list
    aligned_print(out[code]['percentage'], out[code]['desc'])
  File "/Users/maurits/tools/src/i18ndude/src/i18ndude/visualisation.py", line 116, in aligned_print
    print("%s%% - %s" % (percentage, desc))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 11: ordinal not in range(128)
```

When I first do the export (which I added to my bash profile this week), it works fine.

**Comment by gforcada** [comment]
Cool, should we document that on the README or somewhere else?

**Comment by mauritsvanrees** [comment]
I have opened PR #64 to document this.
